### PR TITLE
Use Firebase API to allow user create accounts and login, as well as …

### PR DESCRIPTION
**Pull request by HackBL**
Use Firebase API with cocoapod in order to allow user to create their account and login, also user could reset their password by email

### CODE REVIEW

**Comment by tkevans** [comment]
Hi Bo! I checked your branch it works great! However, you have to resolve the conflicts before we can merge your branch to master. Try to do it by using your terminal.

**Comment by HackBL** [comment]
I've opened new branch called userDB, which has done most of part about user database, as well as pulled request, please check it out

**Comment by tkevans** [comment]
Thank you @bojms45 ! I will take a look at it later. It seems like you have deleted everything on this branch, so I'll close it now.

**Comment by HackBL** [comment]
Yes, I create another branch, and everything is in there, please have a check

**Pull request closed without merging**
