### PR TITLE
Update MenuData.json

### PR DESCRIPTION
**Pull request by XWangCS**
Updated the menu price

### CODE REVIEW

**Comment by tkevans** [comment]
@bojms45 can you review the Json file to see if that's what we want?

**Comment by HackBL** [comment]
OK, Let me review it if we could use it

**Comment by HackBL** [comment]
I create new .json file and store all price data into it

**Comment by HackBL** [comment]
Please close this pull-request without merging, I fixed the bug and merged.

**Comment by tkevans** [comment]
Five days later still no action received from Chelsea. I'll close this PR.

**Pull request closed without merging**
